### ISSUE TITLE
Setup Script Passwords

### ISSUE THREAD

**Issue by antimatter15** [tlsnotary/pagesigner-oracles#5]
https://github.com/tlsnotary/pagesigner-oracles/blob/master/systemd/tlsnotary_setup.sh#L17

Looks like in `tlsnotary_setup.sh` the password for the `notary` user is configured to literally `pass1` rather than the value of the variable `$pass1`

**Comment by themighty1** [comment]
Hi. You are right, thank you. That's a bug. Fixed in the master branch.
