### ISSUE TITLE
Question about make-oracle.sh.

### ISSUE THREAD

**Issue by garyrob** [tlsnotary/pagesigner-oracles#7]
I created a t3a.micro Ubuntu 20.04 LTS  instance with a snap-0c97f1c43c6bb2043 volume. (Such a volume is attached by default to the ami you specified.)

I followed your instructions:

```
sudo apt update && sudo apt install liblz4-tool
git clone --recurse-submodules https://github.com/tlsnotary/pagesigner-oracles
cd pagesigner-oracles
sudo ./make_oracle.sh
```

The complete output from make_oracle.sh was:

```
/
will not modify /dev/nvme0n1p1 because it is mounted on /
```

which doesn't seem right. How can I check whether it worked properly? I'm assuming it didn't, in which case, do you have suggestions for fixing it?

**Comment by themighty1** [comment]
Thanks for your feedback. Did you first launch the t3a.micro instance and after it was launched you attached a "a volume created from snap-0c97f1c43c6bb2043"?
If so, let me try to debug it: what is the output of "sudo blkid"?

**Comment by garyrob** [comment]
I apologize for having to take up your time with what are probably totally newbie questions, but I encourage myself that maybe I'll be able to help refine the wording of the INSTALL page so that it works more easily for other newbies.

I'm not very experienced with AWS, and ended up doing it this way: I went to https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#ImageDetails:imageId=ami-083654bd07b5da81d which allowed me to find the ami you mentioned. And it defaults to having a snap-0c97f1c43c6bb2043 volume that it says is attached to it. I didn't have to do anything to attach it other than basically keep clicking OK to create the instance. So I didn't think that I had to attach another one. Was that assumption wrong?

`sudo blkid` results in:

```
/dev/nvme0n1p1: LABEL="cloudimg-rootfs" UUID="2a29f520-1100-4824-b5d9-d841f1267838" TYPE="ext4" PARTUUID="3fa6b62f-01"
/dev/loop0: TYPE="squashfs"
/dev/loop1: TYPE="squashfs"
/dev/loop2: TYPE="squashfs"
/dev/loop3: TYPE="squashfs"
/dev/loop4: TYPE="squashfs"
/dev/loop5: TYPE="squashfs"
/dev/loop6: TYPE="squashfs"
/dev/loop7: TYPE="squashfs"
/dev/loop8: TYPE="squashfs"

```

**Comment by themighty1** [comment]
yes, I admit that it is confusing having to launch an AMI with snap-0c97f1c43c6bb2043 and then attaching to it another volume from snap-0c97f1c43c6bb2043.
What you can do is launch Ubuntu 18 (insteaf of Ubuntu 20) and then attach to it a volume created from snap-0c97f1c43c6bb2043.

**Comment by garyrob** [comment]
Thanks for you patience! I'm OK just attaching a second one, I just didn't understand what was happening at a basic level. So, I did a little reading, and my current understanding is that the ami contains an associated ebs which has a snapshot containing an OS (in this case Ubuntu 20.04) that we'll  be running. So, what we're trying to do here is launch the ami, which includes a  snap-0c97f1c43c6bb2043, and then attach a second snap-0c97f1c43c6bb2043 in order to modify it. I'll then create an ami that includes that modified snap.

Sorry for such a newbie question! I do think that I may not be unusual, though: a lot of people who may be interested in PageSigner may not know anything about AWS.

**Comment by themighty1** [comment]
yes, correct, the second snap will be modified and the resulting ami will be created from that modified snap. Feel free to ask any more questions, so I could understand how to make the instructions more accesible to those who are not familiar with AWS.

**Comment by themighty1** [comment]
Thanks, I pushed a fix with a clarification to avoid this confusion.
